import React from 'react';
import './TechStack.css';

const pipelineSteps = [
  {
    step: '01',
    title: 'Interface & Input',
    techs: ['Streamlit', 'Custom UI', 'segno'],
    description: 'Students join easily via QR codes generated by Segno. Streamlit and custom React interfaces capture their camera and microphone inputs seamlessly.'
  },
  {
    step: '02',
    title: 'Data Preprocessing',
    techs: ['pillow', 'numpy', 'librosa'],
    description: 'Raw inputs are optimized. Pillow normalizes the facial image frames, while librosa handles audio frequency isolation and noise reduction.'
  },
  {
    step: '03',
    title: 'Biometric Extraction & Matching',
    techs: ['dlib', 'resemblyzer', 'scikit-learn'],
    description: 'dlib extracts a unique 128D facial encoding, and resemblyzer pulls voice embeddings. These are fed into a fast scikit-learn SVC for high-accuracy identity verification.'
  },
  {
    step: '04',
    title: 'Secure Logging & Storage',
    techs: ['Supabase', 'bcrypt'],
    description: 'Passwords are symmetrically hashed using bcrypt. Supabase logs the verified attendance to a PostgreSQL database and streams real-time updates to the dashboard.'
  }
];

export const TechStack = () => {
  return (
    <section className="techstack-section" id="tech-stack">
      <div className="techstack-container">
        <div className="section-header">
          <h2 className="gradient-text">How It Works: The Tech Pipeline</h2>
          <p className="section-subtitle">
            A step-by-step look at how our advanced AI stack processes and verifies attendance in milliseconds.
          </p>
        </div>

        <div className="timeline-container">
          <div className="timeline-line"></div>
          {pipelineSteps.map((step, idx) => (
            <div key={idx} className="timeline-item">
              <div className="timeline-dot-container">
                <div className="timeline-dot"></div>
                <div className="timeline-dot-glow"></div>
              </div>
              <div className="timeline-content glass-panel">
                <div className="step-header">
                  <span className="step-number">{step.step}</span>
                  <h3>{step.title}</h3>
                </div>
                <div className="tech-tags">
                  {step.techs.map((t) => (
                    <span key={t} className="tech-tag">{t}</span>
                  ))}
                </div>
                <p>{step.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};
